### ISSUE TITLE
dont build

### ISSUE THREAD

**Issue by D1abloRUS** [sprocket-fpga/FPGA_Mining_AWS#2]
fpga-miner.c:64:22: fatal error: fpga_pci.h: No such file or directory
before i run:
`cmake . && make`

**Comment by sprocket-fpga** [comment]
That miner only works on AWS F1 instances.  You have to setup the AWS environment before building so all the required files are available.  The fpga_pci.h file is provided by AWS.

**Comment by D1abloRUS** [comment]
@sprocket-fpga sorry, i find this repo https://github.com/aws/aws-fpga

**Comment by sprocket-fpga** [comment]
The best way to learn AWS F1 is to work through one of their tutorials.  For example, this one:

https://github.com/aws/aws-fpga/tree/master/hdk/cl/examples/cl_hello_world

But keep in mind there are lots of steps involved with building a bitstream on AWS and then running it on the F1 instance....it is quite involved and may take quite a bit of time to learn.

**Comment by trustfarm-dev** [comment]
@sprocket-fpga  great share of your resource.
I made TCM-FM1 , it is migrated from vcu1525. and keccak/keccak-c algorithm is evaluated with PCI-E.
https://trustcoinmining.com/bbs/board.php?bo_table=notice&wr_id=22 

are you interested develop bitstream for this board?

send me a email : cpplover@trustfarm.net  or telegram , wechat : trustfarm 

thanks.
