### ISSUE TITLE
many hw errors with tribus.

### ISSUE THREAD

**Issue by xiamike** [sprocket-fpga/FPGA_Mining_AWS#3]
Hi Sprocket,

First off thanks for sharing, these were great learning resources and a lot of fun to dive into.  I managed to get a few of them running on F1 instances like grs, myr-grs, and phi1612.  After a lot of reading and guide digging and discord question asking lol ...

However having a lot of HW errors with Tribus.  The `.c` version of tribus_hash is working fine, so I think it's either how the data is being written and read from the FPGA.  

Any clues?  I saw a lot of commented out code.  

Mike

**Comment by xiamike** [comment]
Oh also was chatting with DC and senseless in discord, they think it's an endianess issue.  

I plan on using vivado and putting some debug probes to take a peek inside, never done it before though.

**Comment by xiamike** [comment]
Ohhhh, got it is that why you subtract `CORES * OFFSET` from the nonce?  

then after OFFSET cycles, it will return to the correct nonce number?

**Comment by xiamike** [comment]
@sprocket-fpga someone in discord suggested we just add 42 to the nonce that's reported, would that correct the `nonce_out` read or is this a hardware change that needs to happen?

**Comment by xiamike** [comment]
@sprocket-fpga someone in discord suggested we just add 42 to the nonce that's reported, would that correct the `nonce_out` read or is this a hardware change that needs to happen?

**Comment by sprocket-fpga** [comment]
you can correct the issue either way...both work.

**Comment by xiamike** [comment]
Hmm, I made the below change to the `aws_miner_thread`.  

```
// Calculate Hash Using Nonce From FPGA
work.data[g_fpga_nonce_idx] = nonce + 52;
calc_hash((unsigned char *)work.data, (unsigned char *)hash);

// Check If Hash < Target Sent To FPGA
if (swab32(hash[7]) > swab32(target[7])) {
	fpga->hw_errors++;
	applog(LOG_DEBUG, "%s: HW Error (Nonce: %08X, Hash: %08X, Target: %08X)", fpga->short_name, nonce, swab32(hash[7]), swab32(target[7]));
	continue;
}
```

assuming the offset went from 242 to 294?  the nonce should be off by 52 cycles right?

**Comment by sprocket-fpga** [comment]
you'll have to do the math yourself to get the right number.  Unfortunately, I don't have any free time to work on this right now.  I have provide the updated miner.v which should address the issue.

**Comment by xiamike** [comment]
@sprocket-fpga gotcha yeah thanks a bunch for that.  I'll go figure it out, appreciate the help.  

just knowing that it's possible / this was the issue is a tremendous help.  I literally spent 4 days straight dissecting `fpga_miner.c` thinking it was a entirely different issue.  would have never guessed to do this.  

thx much!  🙏

**Comment by xiamike** [comment]
@sprocket-fpga thanks that did it!  working beautifully now.  any idea how to permanently delete this issue?  people are starting to email me at my commit log email 😞

**Comment by xiamike** [comment]
hey sprocket, thanks so much again.  I took the tribus RTL's and synthesized my own design.  wanted to confirm my math with you.  

The cores are running at 250Mhz, and since it takes 294 clock cycles to generate a valid hash, does this mean I'm getting 250M clks divide by 294 clks/hash * 2 cores = 1.7 GH/s?

**Comment by sprocket-fpga** [comment]
unfortunately, your math is not correct.  The logic is running at 250mhz using pipelines.  So what that means is once the pipeline is full, it will produce one valid hash every clock, so 250MH/s.  If you have 2 cores, then it just means you produce 2 hashes per clock, so 500MH/s total.

So what you'll want to work at is a) either fitting more cores on the chip...it should hold 3 no problem, and b) tweaking the algo to run at a considerably higher clock speed such as 400mhz.

Then, it would probably take overclocking to gain even more performance to run at the hashrate you were quoting.

**Comment by xiamike** [comment]
@sprocket-fpga ah okay, that makes sense.  sorry haven't had much sleep sorry, couldn't really do math sigh.  

I was seeing 600 on AWS, so I'm guessing that it was using the 300Mhz clock recipe.  So sounds like I'm a long ways off from whitefire's 2.1GHz 😂

I guess to get to 2.1, he probably has 3 cores and managed to push it to 700MHz?  damn that's crazy, feels so far off lol...
